# Generated by Django 3.0.4 on 2020-05-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
